# -*- coding: utf-8 -*-
"""preguntas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n2vwjd84Cfre4-zk1wK9b2SjypkBucdc
"""

def jugar_cuestionario():
    """
    Ejecuta un cuestionario interactivo con feedback visual.
    """
    preguntas = [
        {
            "pregunta": "¿Qué describe mejor la criptografía según el documento?",
            "opciones": {
                "A": "Un método para acelerar la transmisión de datos.",
                "B": "La práctica de desarrollar algoritmos codificados para proteger información.",
                "C": "Un sistema para reducir el tamaño de los archivos.",
                "D": "Un protocolo de comunicación inalámbrica."
            },
            "respuesta_correcta": "B"
        },
        {
            "pregunta": "¿Cuál de los siguientes principios busca evitar que el remitente niegue haber enviado información?",
            "opciones": {
                "A": "Confidencialidad",
                "B": "Integridad",
                "C": "Autenticación",
                "D": "No repudio"
            },
            "respuesta_correcta": "D"
        },
                {
            "pregunta": "¿ En la criptografía simétrica, ¿qué característica la define?",
            "opciones": {
                "A": "Usa diferentes claves para cifrar y descifrar",
                "B": "Usa la misma clave para cifrar y descifrar la información",
                "C": "No requiere claves",
                "D": "Depende del uso de firmas digitales",
            },
            "respuesta_correcta": "B"
        },
                        {
            "pregunta": "¿Cuál es una ventaja destacada de la criptografía simétrica?",
            "opciones": {
                "A": "Es lenta pero más segura",
                "B": "Es rápida y eficiente para grandes volúmenes de datos",
                "C": "No necesita intercambio de claves",
                "D": ") No requiere recursos computacionales"
            },
            "respuesta_correcta": "B"
        },
                        {
            "pregunta": "¿Qué tipo de criptografía utiliza un par de claves relacionadas matemáticamente (una pública y una privada)?",
            "opciones": {
                "A": "Criptografía simétrica",
                "B": "Criptografía asimétrica",
                "C": "Criptografía híbrida",
                "D": "Criptografía cuántica"
            },
            "respuesta_correcta": "B"
        },
                {
            "pregunta": "¿Cuál de los siguientes algoritmos es un ejemplo de criptografía asimétrica?",
            "opciones": {
                "A": "AES",
                "B": "RSA",
                "C": "SHA-256",
                "D": "HMAC"
            },
            "respuesta_correcta": "B"
        },
                        {
            "pregunta": "¿Qué ventaja tiene la criptografía por hardware en comparación con la de software?",
            "opciones": {
                "A": "Permite mayor flexibilidad de actualización",
                "B": "Es más económica de implementar",
                "C": "Proporciona seguridad física y mejor rendimiento",
                "D": "No requiere dispositivos adicionales"
            },
            "respuesta_correcta": "C"
        },
                        {
            "pregunta": "¿Cuál es la función principal de una firma digital según el documento?",
            "opciones": {
                "A": "Comprimir los datos cifrados",
                "B": "Garantizar integridad, autenticidad y no repudio",
                "C": "Aumentar la velocidad del cifrado",
                "D": "Reemplazar las claves públicas"
            },
            "respuesta_correcta": "B"
        },
                                {
            "pregunta": "¿Qué ventaja ofrece la criptografía de curva elíptica (ECC)?",
            "opciones": {
                "A": "Permite la transmisión sin cifrado",
                "B": "Requiere claves más grandes para mantener la seguridad",
                "C": "Ofrece el mismo nivel de protección con claves más pequeñas",
                "D": "Solo funciona en entornos financieros"
            },
            "respuesta_correcta": "C"
        },
                                {
            "pregunta": "¿Qué objetivo tiene la criptografía poscuántica (PQC) mencionada en el documento?",
            "opciones": {
                "A": "Sustituir la criptografía en riesgo ante computadoras cuánticas",
                "B": " Reducir los costos del hardware criptográfico",
                "C": "Eliminar el uso de claves pública",
                "D": "Mejorar la estética del código fuente"
            },
            "respuesta_correcta": "A"
        },
    ]

    print("--- 🧠 ¡Bienvenido al Cuestionario de Ciberseguridad! ---")

    puntuacion = 0

    for i, item in enumerate(preguntas):
        print(f"\n### *{i + 1}. {item['pregunta']}*")

        # Mostrar opciones
        for clave, valor in item['opciones'].items():
            print(f"  {clave}) {valor}")

        respuesta_valida = False
        while not respuesta_valida:
            # Solicitar respuesta
            respuesta_usuario = input("Tu respuesta (Escribe A, B, C o D): ").strip().upper()

            # Verificar si la respuesta es una opción válida
            if respuesta_usuario in item['opciones']:
                respuesta_valida = True

                # Comprobar la respuesta
                if respuesta_usuario == item['respuesta_correcta']:
                    print("🎉 ✅ ¡Correcto! La respuesta es:", item['opciones'][respuesta_usuario])
                    puntuacion += 1
                else:
                    print(f"❌ Intenta de nuevo. La respuesta correcta era: {item['respuesta_correcta']}")
            else:
                print("⚠️ Opción no válida. Por favor, escribe solo la letra de la opción (A, B, C o D).")

    print("\n--- 🌟 Cuestionario Finalizado ---")
    print(f"Obtuviste {puntuacion} de {len(preguntas)} respuestas correctas.")

# Ejecutar la función del juego
if __name__ == "__main__":
    jugar_cuestionario()